/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package main.kotlin.bowlingGame

class BowlingGame {
    fun roll(i: Int) {

    }

    fun start() {

    }

    fun score(): Int? {
        return 0
    }

}

fun main(args: Array<String>) {
    BowlingGame().start()
}
