/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package main.kotlin.bowlingGame

import main.kotlin.bowlingGame.model.Frame

class BowlingGame {
    var playedFrames = mutableListOf<Frame>()

    fun roll(i: Int) {
        if (playedFrames.isNotEmpty() &&
                playedFrames.last().mayRollAgain()) {
            playedFrames.last().roll(i)
        } else {
            val frame = Frame()
            frame.roll(i)
            playedFrames.add(frame)
        }
    }

    fun start() {

    }

    fun score(): Int? {
        var score = 0

        val it = playedFrames.iterator()
        while (it.hasNext()) {
            score += it.next().score()
        }

        return score
    }
}

fun main(args: Array<String>) {
    BowlingGame().start()
}
