/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package test.kotlin.bowlingGame

import main.kotlin.bowlingGame.BowlingGame
import org.hamcrest.core.IsEqual.equalTo
import org.junit.Assert.assertThat
import org.junit.Before
import org.junit.Test

class BowlingGameTest {

    private lateinit var game: BowlingGame

    @Before
    fun setUp() {
        game = BowlingGame()
    }

    private fun rollSpare() {
        game.roll(5)
        game.roll(5) // Spar
    }

    private fun rollStrike() {
        game.roll(10)
    }

    private fun rollPinsNTimes(times: Int, pins: Int) {
        for (i in 0 until times) {
            game.roll(pins)
        }
    }

    @Test
    fun testAppScoreEqualsToZeroWhenTenMiss() {
        rollPinsNTimes(10, 0)
        assertThat(game.score(), equalTo(0))
    }

    @Test
    fun testAppScoreEqualsToTenWhenTenOne() {
        rollPinsNTimes(10, 1)
        assertThat("Just counting pin in standard cases", game.score(), equalTo(10))
    }

    @Test
    fun testWithSpare() {
        rollSpare()
        game.roll(5)

        rollPinsNTimes(17, 0)
        assertThat("On Spare you must add only next roll to current score", game.score(), equalTo(20))
    }

    @Test
    fun testWithStrike() {
        rollStrike()
        game.roll(5)
        game.roll(4)

        rollPinsNTimes(16, 0)
        assertThat("On strike you must add the two next roll", game.score(), equalTo(28))
    }
}
