/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package test.kotlin.bowlingGame

import main.kotlin.bowlingGame.BowlingGame
import org.hamcrest.core.IsEqual.equalTo
import org.junit.Assert.assertThat
import org.junit.Test

class BowlingGameTest {
    @Test
    fun testAppScoreEqualsToZeroWhenTenMiss() {
        val game = BowlingGame()
        for(i in 0..10) {
            game.roll(0)
        }

        assertThat(game.score(), equalTo(0))
    }
}
